=== lsvbs/oc-declare-simulator/Backend/tests/fixtures/ocel20-schema-json.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "eventTypes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "attributes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "type"
              ]
            }
          }
        },
        "required": [
          "name",
          "attributes"
        ]
      }
    },
    "objectTypes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "attributes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "type"
              ]
            }
          }
        },
        "required": [
          "name",
          "attributes"
        ]
      }
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "time": {
            "type": "string",
            "format": "date-time"
          },
          "attributes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "value"
              ]
            }
          },
          "relationships": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "objectId": {
                  "type": "string"
                },
                "qualifier": {
                  "type": "string"
                }
              },
              "required": [
                "objectId",
                "qualifier"
              ]
            }
          }
        },
        "required": [
          "id",
          "type",
          "time"
        ]
      }
    },
    "objects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "relationships": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "objectId": {
                  "type": "string"
                },
                "qualifier": {
                  "type": "string"
                }
              },
              "required": [
                "objectId",
                "qualifier"
              ]
            }
          },
          "attributes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                },
                "time": {
                  "type": "string",
                  "format": "date-time"
                }
              },
              "required": [
                "name",
                "value",
                "time"
              ]
            }
          }
        },
        "required": [
          "id",
          "type"
        ]
      }
    }
  },
  "required": [
    "eventTypes",
    "objectTypes",
    "events",
    "objects"
  ]
}

=== lsvbs/oc-declare-simulator/src/Simulation/IO/input/eventlog/Example_OCEL_arrow_DF.json
{
  "eventTypes": [
    {
      "name": "Submit Manuscript",
      "attributes": []
    },
    {
      "name": "Review Manuscript",
      "attributes": []
    }
  ],
  "objectTypes": [
    {
      "name": "manuscript",
      "attributes": []
    }
  ],
  "objects": [
    {
      "id": "m1",
      "type": "manuscript",
      "attributes": [],
      "relationships": []
    },
    {
      "id": "m2",
      "type": "manuscript",
      "attributes": [],
      "relationships": []
    },
    {
      "id": "m3",
      "type": "manuscript",
      "attributes": [],
      "relationships": []
    }
  ],
  "events": [
    {
      "id": "e1",
      "type": "Submit Manuscript",
      "time": "2026-01-01T09:00:00Z",
      "attributes": [],
      "relationships": [
        {
          "objectId": "m1",
          "qualifier": "manuscript"
        }
      ]
    },
    {
      "id": "e2",
      "type": "Review Manuscript",
      "time": "2026-01-02T09:00:00Z",
      "attributes": [],
      "relationships": [
        {
          "objectId": "m1",
          "qualifier": "manuscript"
        }
      ]
    },
    {
      "id": "e3",
      "type": "Submit Manuscript",
      "time": "2026-01-03T09:00:00Z",
      "attributes": [],
      "relationships": [
        {
          "objectId": "m2",
          "qualifier": "manuscript"
        }
      ]
    },
    {
      "id": "e4",
      "type": "Review Manuscript",
      "time": "2026-01-04T09:00:00Z",
      "attributes": [],
      "relationships": [
        {
          "objectId": "m2",
          "qualifier": "manuscript"
        }
      ]
    },
    {
      "id": "e5",
      "type": "Review Manuscript",
      "time": "2026-01-05T09:00:00Z",
      "attributes": [],
      "relationships": [
        {
          "objectId": "m3",
          "qualifier": "manuscript"
        }
      ]
    }
  ]
}
